from typing import Protocol


class ObjectStore(Protocol):
    def put_json(self, key: str, payload: dict) -> None: ...

    def get_json(self, key: str) -> dict: ...

    def list_keys(self, prefix: str = '') -> list[str]: ...

    def exists(self, key: str) -> bool: ...
